[build]
publish = "ANerdyPlace/public"
command = "cd ANerdyPlace && hugo --gc --minify --themesDir themes"

[context.production.environment]
HUGO_VERSION = "0.92.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "repo"

[context.split1]
command = "cd ANerdyPlace && hugo --gc --minify --enableGitInfo --themesDir themes"

[context.split1.environment]
HUGO_VERSION = "0.92.0"
HUGO_ENV = "production"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd ANerdyPlace && hugo --gc --minify --buildFuture --themesDir themes -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.0"
HUGO_THEME = "repo"

[context.branch-deploy]
command = "cd ANerdyPlace && hugo --gc --minify --themesDir themes -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.92.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
