baseURL: "https://anerdyplace.org/"
languageCode: "en-us"
title: "A Nerdy Place"
theme: hugo-profile

Paginate: 12
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
      
    # - identifier: tags
      # name: Tags
      # title: Tags
      # url: /tags
      # weight: 2
      
    - identifier: search
      name: Search
      title: Search
      url: /search
      weight: 2
    
    # - identifier: songs
    #   name: Songs
    #   title: Songs
    #   url: /songs
    #   weight: 3

    # - identifier: gallery
      # name: Gallery
      # title: Blog posts
      # url: /gallery
      # weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "A Nerdy Place"
  description: My personal profile and blogging site.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/icon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, I'm"
    title: "Philipp"
    subtitle: "Unger"
    content: "Software developer - maker - artist"
    image: /images/profile-pic-4.jpg
    # button:
      # enable: true
      # name: "Resume"
      # url: "#"
      # download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/GrafKnusprig
        - icon: fab fa-soundcloud
          url: https://soundcloud.com/mufuki
        - icon: fab fa-youtube
          url: https://www.youtube.com/channel/UCJ29i8qd-09tz47yZP7lxrA
        - icon: fas fa-laugh
          url: https://www.thingiverse.com/search?q=grafknusprig
        # - icon: fab fa-twitter
          # url: https://example.com
      # customIcons:
        # - icon: /fav.png
          # url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    # image: "/images/profile-pic-1.webp"
    content: |-
      When you ask someone to tell you something about themselves, it's never easy.

      I have always been interested in all kinds of things all my life. My interests are constantly changing and I always want to learn new things.
      If I have to describe myself in a few words, I would say I am a craftsman and an artist.

      After finishing school I studied Computer Science and now I have several years of professional experience as a software developer.
      But I am not the type for only one thing and so I have a lot of hobbies. I have always been interested in designing and customizing everything all my life. I like to paint and draw, design things for friends like logos, websites, paint jobs, etc. I also have an affinity for photography, film and music and always try to get better.
      I'm also very interested in doing everything with open source software if possible, which I'm a big proponent of. And the most of the things I code, produce or design, I realease as Creative Commons.
      The PC has always been a constant companion in all my projects and I always try to make my life easier with it. I design a lot and often write tools and small programs that help me with my work.
      <br><br><br>
      On this website I try to blog about my projects. But I have so much to catch up on and most of the time I just don't think about it and forget it.
      But then I think to myself again: Even a little bit of something is still better than nothing.

      We'll see what the future brings and if I can pull this off.
      Keep your fingers crossed for me ;)
      <br><br><br><br><br>

    skills:
      enable: true
      title: "I just put some things I work with here :)"
      items:
        - "[AdobeSuite](https://www.adobe.com/creativecloud.html)"
        - "[Blender](https://www.blender.org/)"
        - "[FDM 3D printing](https://ultimaker.com/software/ultimaker-cura)"
        - "[C# / .Net](https://docs.microsoft.com/en-us/dotnet/csharp/)"
        - "[ffmpeg](https://ffmpeg.org/)"
        - "[GitHub](https://github.com/)"
        - "[HUGO](https://gohugo.io/)"
        - "[JavaScript](https://www.w3schools.com/js/)"
        - "[MPC Beats](https://www.akaipro.com/mpc-beats)"
        - "[Node.js](https://nodejs.org/en/)"
        - "[OpenSCAD](https://openscad.org/)"
        - "[VisualStudio](https://visualstudio.microsoft.com)"

  # Experience
  experience:
    enable: true
    title: "Professional Experience"
    items:
      - job: "Software Developer"
        company: "DAP Systems"
        companyUrl: "https://dap-systems.de/"
        date: "2014 - present"
        # featuredlink:
          # enable: true
          # name: "view the project"
          # url: "https://example.com"
        content: |-
          I am currently working as a software developer at [DAP Systems.](https://dap-systems.de/) in Passau, BY Germany.
          - Fullstack developer for WebReporting, ImageSurfer, RadioXpert-Web [2019 - present]
          - Backend developer for RadioXpert, Evogenius Reporting, TVScope [2014 - 2019]
          
          I have experience in ASP.NET, Angular, C#, CSS, EXT JS, HTML, JavaScript, Less, .Net Framework / Core, Node.js, PHP, SQL, TypeScript and more.

      - job: "Media Computer Scientist"
        company: "University of Passau"
        companyUrl: "https://www.uni-passau.de/en/"
        date: "2013 - 2014"
        # featuredLink:
          # enable: true
          # name: "Univideo Website"
          # url: "https://univideo.uni-passau.de/"
        # info:
          # enable: true
          # content: I worked as a software developer for the univideo website and more.
        content: I worked as a web developer for the [univideo website](https://univideo.uni-passau.de/) and more. Doing mainly HTML, CSS and JS.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Bachelor of Computer Science"
        school:
          name: "University of Passau"
          url: "https://www.uni-passau.de/en/"
        date: "2009 - 2013"
        # GPA: "3.9 out of 5.0"
        content: |-
          Minor:  **Business Administration**

          Bachelor thesis:
            - [**Automatisierung der Kartographierung von Straßenschildern (Automated street sign mapping)**](https://www.forwiss.uni-passau.de/extern/doc/BA_Unger.pdf)
              
              [FORWISS](https://www.forwiss.uni-passau.de/en/), University of Passau, [Chair of Mathematics with focus on Digital Image Processing](https://www.fim.uni-passau.de/en/digital-image-processing/)
        # featuredLink:
          # enable: true
          # name: "My academic record"
          # url: "https://example.com"
      - title: "High School"
        school:
          name: "Maristengymnasium Fürstenzell"
          url: "http://www.mgfuerstenzell.de/"
        content: |-
            - Advanced courses:
              - physics
              - art
            - Senior project: Digital and craft implementation of a 3D optical illusion

  # Achievements
  # achievements:
    # enable: true
    # # title: "Custom Name"
    # items:
      # - title: Google kickstart runner
        # content: I solved all problems with optimal solution.
        # url: https://example.com
      # - title: Facebook Hackathon Winner
        # content: Developed a product using Artificial Intelligence.
      # - title: Hugo Profile
        # content: Developed a theme and getting 1K+ downloads per month.
        # url: "https://github.com/gurusabarish/hugo-profile"
      # - title: Microsoft Imagine Runner
        # content: We are developed a product which can help others.
      # - title: Google Summer of Code
        # content: Contributed to a open source project.
        # url: https://example.com

  # projects
  projects:
    enable: true
    # title: "custom name"
    items:
      - title: "Hunt: Showdown - Loadout Randomizer"
        content: "Hunt: Showdown - Loadout Randomizer is a local browser application that generates random loadouts for the game Hunt: Showdown. It is perfectly suited to be used as a browser plugin in OBS-Studio and similar applications and was made exactly for this purpose."
        image: /images/projects/hunt-randomizer-1.webp
        featured:
          name: Start Randomizer
          link: https://grafknusprig.github.io/HuntShowdownLoadoutRandomizer/Randomizer.html
        badges:
          - "html"
          - "javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/GrafKnusprig/HuntShowdownLoadoutRandomizer
      # - title: "Tin Whistles"
      #   content: "A passion of mine is to build and play my own tin whistles."
      #   image: /blogs/3d/tin-whistle/thumb-1.webp
      #   featured:
      #     name: Read Blog Post
      #     link: /blogs/3d/tin-whistle/tin-whistle-1
      #   badges:
      #     - "blender"
      #     - "OpenSCAD"
      #     - "3D printing"

  #Contact
  contact:
    enable: true
    title: "Contact me"
    content: If you want to contact me, you can always send me an email.
    email: philipp.info@proton.me
    btnName: Mail me

  footer:
    recentPosts: true
    # socialNetworks:
      # github: https://github.com
      # linkedin: https://linkedin.com
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

outputs:
  home:
    - HTML
    - JSON